# -*- coding: utf-8 -*-
"""insert_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inbe7G4izTFZLuISvZ2wSC028vLJURpu
"""

import pandas as pd

pip install psycopg2

# Load the dataset
dataset_path = "/content/IMDB Dataset.csv"
df = pd.read_csv(dataset_path, on_bad_lines='skip')

df.head()

df.describe()

df.shape

df.isnull().sum()

import psycopg2

# Database connection details
conn = psycopg2.connect(
    dbname="demodb",
    user="postgres",
    password="Pallav00@",
    host="localhost",
    port="5432"
)
cursor = conn.cursor()

# Query the data
query = "SELECT * FROM imdb_reviews"
df = pd.read_sql(query, conn)

# Analyze the data
print(df['sentiment'].value_counts())
conn.close()

